// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// NOTE: DO NOT EDIT --- This file is automatically generated by sync.py.

import { ContentTypeInfo } from "./content-type-info.js";
import { ContentTypeLabel } from "./content-type-label.js";

export type ContentTypesInfos = Record<ContentTypeLabel, ContentTypeInfo>;

export const ContentTypesInfos = {
  get: (): ContentTypesInfos => ({
    [ContentTypeLabel._3DS]: {
      label: ContentTypeLabel._3DS,
      is_text: false,
    },
    [ContentTypeLabel._3DSM]: {
      label: ContentTypeLabel._3DSM,
      is_text: false,
    },
    [ContentTypeLabel._3DSX]: {
      label: ContentTypeLabel._3DSX,
      is_text: false,
    },
    [ContentTypeLabel._3GP]: {
      label: ContentTypeLabel._3GP,
      is_text: false,
    },
    [ContentTypeLabel._3MF]: {
      label: ContentTypeLabel._3MF,
      is_text: false,
    },
    [ContentTypeLabel.ABNF]: {
      label: ContentTypeLabel.ABNF,
      is_text: false,
    },
    [ContentTypeLabel.ACE]: {
      label: ContentTypeLabel.ACE,
      is_text: false,
    },
    [ContentTypeLabel.ADA]: {
      label: ContentTypeLabel.ADA,
      is_text: false,
    },
    [ContentTypeLabel.AFF]: {
      label: ContentTypeLabel.AFF,
      is_text: true,
    },
    [ContentTypeLabel.AI]: {
      label: ContentTypeLabel.AI,
      is_text: false,
    },
    [ContentTypeLabel.AIDL]: {
      label: ContentTypeLabel.AIDL,
      is_text: true,
    },
    [ContentTypeLabel.ALGOL68]: {
      label: ContentTypeLabel.ALGOL68,
      is_text: false,
    },
    [ContentTypeLabel.ANI]: {
      label: ContentTypeLabel.ANI,
      is_text: false,
    },
    [ContentTypeLabel.APK]: {
      label: ContentTypeLabel.APK,
      is_text: false,
    },
    [ContentTypeLabel.APPLEBPLIST]: {
      label: ContentTypeLabel.APPLEBPLIST,
      is_text: false,
    },
    [ContentTypeLabel.APPLEDOUBLE]: {
      label: ContentTypeLabel.APPLEDOUBLE,
      is_text: false,
    },
    [ContentTypeLabel.APPLEPLIST]: {
      label: ContentTypeLabel.APPLEPLIST,
      is_text: true,
    },
    [ContentTypeLabel.APPLESINGLE]: {
      label: ContentTypeLabel.APPLESINGLE,
      is_text: false,
    },
    [ContentTypeLabel.AR]: {
      label: ContentTypeLabel.AR,
      is_text: false,
    },
    [ContentTypeLabel.ARC]: {
      label: ContentTypeLabel.ARC,
      is_text: false,
    },
    [ContentTypeLabel.ARJ]: {
      label: ContentTypeLabel.ARJ,
      is_text: false,
    },
    [ContentTypeLabel.ARROW]: {
      label: ContentTypeLabel.ARROW,
      is_text: false,
    },
    [ContentTypeLabel.ASC]: {
      label: ContentTypeLabel.ASC,
      is_text: true,
    },
    [ContentTypeLabel.ASD]: {
      label: ContentTypeLabel.ASD,
      is_text: false,
    },
    [ContentTypeLabel.ASF]: {
      label: ContentTypeLabel.ASF,
      is_text: false,
    },
    [ContentTypeLabel.ASM]: {
      label: ContentTypeLabel.ASM,
      is_text: true,
    },
    [ContentTypeLabel.ASP]: {
      label: ContentTypeLabel.ASP,
      is_text: true,
    },
    [ContentTypeLabel.AU]: {
      label: ContentTypeLabel.AU,
      is_text: false,
    },
    [ContentTypeLabel.AUTOHOTKEY]: {
      label: ContentTypeLabel.AUTOHOTKEY,
      is_text: true,
    },
    [ContentTypeLabel.AUTOIT]: {
      label: ContentTypeLabel.AUTOIT,
      is_text: true,
    },
    [ContentTypeLabel.AVI]: {
      label: ContentTypeLabel.AVI,
      is_text: false,
    },
    [ContentTypeLabel.AVIF]: {
      label: ContentTypeLabel.AVIF,
      is_text: false,
    },
    [ContentTypeLabel.AVRO]: {
      label: ContentTypeLabel.AVRO,
      is_text: false,
    },
    [ContentTypeLabel.AWK]: {
      label: ContentTypeLabel.AWK,
      is_text: true,
    },
    [ContentTypeLabel.AX]: {
      label: ContentTypeLabel.AX,
      is_text: false,
    },
    [ContentTypeLabel.BATCH]: {
      label: ContentTypeLabel.BATCH,
      is_text: true,
    },
    [ContentTypeLabel.BAZEL]: {
      label: ContentTypeLabel.BAZEL,
      is_text: true,
    },
    [ContentTypeLabel.BCAD]: {
      label: ContentTypeLabel.BCAD,
      is_text: false,
    },
    [ContentTypeLabel.BIB]: {
      label: ContentTypeLabel.BIB,
      is_text: true,
    },
    [ContentTypeLabel.BMP]: {
      label: ContentTypeLabel.BMP,
      is_text: false,
    },
    [ContentTypeLabel.BPG]: {
      label: ContentTypeLabel.BPG,
      is_text: false,
    },
    [ContentTypeLabel.BPL]: {
      label: ContentTypeLabel.BPL,
      is_text: false,
    },
    [ContentTypeLabel.BRAINFUCK]: {
      label: ContentTypeLabel.BRAINFUCK,
      is_text: true,
    },
    [ContentTypeLabel.BRF]: {
      label: ContentTypeLabel.BRF,
      is_text: false,
    },
    [ContentTypeLabel.BZIP]: {
      label: ContentTypeLabel.BZIP,
      is_text: false,
    },
    [ContentTypeLabel.BZIP3]: {
      label: ContentTypeLabel.BZIP3,
      is_text: false,
    },
    [ContentTypeLabel.C]: {
      label: ContentTypeLabel.C,
      is_text: true,
    },
    [ContentTypeLabel.CAB]: {
      label: ContentTypeLabel.CAB,
      is_text: false,
    },
    [ContentTypeLabel.CAD]: {
      label: ContentTypeLabel.CAD,
      is_text: false,
    },
    [ContentTypeLabel.CAT]: {
      label: ContentTypeLabel.CAT,
      is_text: false,
    },
    [ContentTypeLabel.CDF]: {
      label: ContentTypeLabel.CDF,
      is_text: false,
    },
    [ContentTypeLabel.CHM]: {
      label: ContentTypeLabel.CHM,
      is_text: false,
    },
    [ContentTypeLabel.CLOJURE]: {
      label: ContentTypeLabel.CLOJURE,
      is_text: true,
    },
    [ContentTypeLabel.CMAKE]: {
      label: ContentTypeLabel.CMAKE,
      is_text: true,
    },
    [ContentTypeLabel.COBOL]: {
      label: ContentTypeLabel.COBOL,
      is_text: true,
    },
    [ContentTypeLabel.COFF]: {
      label: ContentTypeLabel.COFF,
      is_text: false,
    },
    [ContentTypeLabel.COFFEESCRIPT]: {
      label: ContentTypeLabel.COFFEESCRIPT,
      is_text: true,
    },
    [ContentTypeLabel.COM]: {
      label: ContentTypeLabel.COM,
      is_text: false,
    },
    [ContentTypeLabel.CPL]: {
      label: ContentTypeLabel.CPL,
      is_text: false,
    },
    [ContentTypeLabel.CPP]: {
      label: ContentTypeLabel.CPP,
      is_text: true,
    },
    [ContentTypeLabel.CRT]: {
      label: ContentTypeLabel.CRT,
      is_text: false,
    },
    [ContentTypeLabel.CRX]: {
      label: ContentTypeLabel.CRX,
      is_text: false,
    },
    [ContentTypeLabel.CS]: {
      label: ContentTypeLabel.CS,
      is_text: true,
    },
    [ContentTypeLabel.CSPROJ]: {
      label: ContentTypeLabel.CSPROJ,
      is_text: true,
    },
    [ContentTypeLabel.CSS]: {
      label: ContentTypeLabel.CSS,
      is_text: true,
    },
    [ContentTypeLabel.CSV]: {
      label: ContentTypeLabel.CSV,
      is_text: true,
    },
    [ContentTypeLabel.CTL]: {
      label: ContentTypeLabel.CTL,
      is_text: false,
    },
    [ContentTypeLabel.DART]: {
      label: ContentTypeLabel.DART,
      is_text: true,
    },
    [ContentTypeLabel.DEB]: {
      label: ContentTypeLabel.DEB,
      is_text: false,
    },
    [ContentTypeLabel.DEX]: {
      label: ContentTypeLabel.DEX,
      is_text: false,
    },
    [ContentTypeLabel.DEY]: {
      label: ContentTypeLabel.DEY,
      is_text: false,
    },
    [ContentTypeLabel.DICOM]: {
      label: ContentTypeLabel.DICOM,
      is_text: false,
    },
    [ContentTypeLabel.DIFF]: {
      label: ContentTypeLabel.DIFF,
      is_text: true,
    },
    [ContentTypeLabel.DIRECTORY]: {
      label: ContentTypeLabel.DIRECTORY,
      is_text: false,
    },
    [ContentTypeLabel.DJANGO]: {
      label: ContentTypeLabel.DJANGO,
      is_text: false,
    },
    [ContentTypeLabel.DLL]: {
      label: ContentTypeLabel.DLL,
      is_text: false,
    },
    [ContentTypeLabel.DM]: {
      label: ContentTypeLabel.DM,
      is_text: true,
    },
    [ContentTypeLabel.DMG]: {
      label: ContentTypeLabel.DMG,
      is_text: false,
    },
    [ContentTypeLabel.DMIGD]: {
      label: ContentTypeLabel.DMIGD,
      is_text: true,
    },
    [ContentTypeLabel.DMSCRIPT]: {
      label: ContentTypeLabel.DMSCRIPT,
      is_text: true,
    },
    [ContentTypeLabel.DOC]: {
      label: ContentTypeLabel.DOC,
      is_text: false,
    },
    [ContentTypeLabel.DOCKERFILE]: {
      label: ContentTypeLabel.DOCKERFILE,
      is_text: true,
    },
    [ContentTypeLabel.DOCX]: {
      label: ContentTypeLabel.DOCX,
      is_text: false,
    },
    [ContentTypeLabel.DOSMBR]: {
      label: ContentTypeLabel.DOSMBR,
      is_text: false,
    },
    [ContentTypeLabel.DOTX]: {
      label: ContentTypeLabel.DOTX,
      is_text: false,
    },
    [ContentTypeLabel.DSSTORE]: {
      label: ContentTypeLabel.DSSTORE,
      is_text: false,
    },
    [ContentTypeLabel.DWG]: {
      label: ContentTypeLabel.DWG,
      is_text: false,
    },
    [ContentTypeLabel.DXF]: {
      label: ContentTypeLabel.DXF,
      is_text: true,
    },
    [ContentTypeLabel.DYLIB]: {
      label: ContentTypeLabel.DYLIB,
      is_text: false,
    },
    [ContentTypeLabel.EBML]: {
      label: ContentTypeLabel.EBML,
      is_text: false,
    },
    [ContentTypeLabel.ELF]: {
      label: ContentTypeLabel.ELF,
      is_text: false,
    },
    [ContentTypeLabel.ELIXIR]: {
      label: ContentTypeLabel.ELIXIR,
      is_text: true,
    },
    [ContentTypeLabel.EMF]: {
      label: ContentTypeLabel.EMF,
      is_text: false,
    },
    [ContentTypeLabel.EML]: {
      label: ContentTypeLabel.EML,
      is_text: true,
    },
    [ContentTypeLabel.EMPTY]: {
      label: ContentTypeLabel.EMPTY,
      is_text: false,
    },
    [ContentTypeLabel.EPUB]: {
      label: ContentTypeLabel.EPUB,
      is_text: false,
    },
    [ContentTypeLabel.ERB]: {
      label: ContentTypeLabel.ERB,
      is_text: true,
    },
    [ContentTypeLabel.ERLANG]: {
      label: ContentTypeLabel.ERLANG,
      is_text: true,
    },
    [ContentTypeLabel.ESE]: {
      label: ContentTypeLabel.ESE,
      is_text: false,
    },
    [ContentTypeLabel.EXE]: {
      label: ContentTypeLabel.EXE,
      is_text: false,
    },
    [ContentTypeLabel.EXP]: {
      label: ContentTypeLabel.EXP,
      is_text: false,
    },
    [ContentTypeLabel.FLAC]: {
      label: ContentTypeLabel.FLAC,
      is_text: false,
    },
    [ContentTypeLabel.FLUTTER]: {
      label: ContentTypeLabel.FLUTTER,
      is_text: false,
    },
    [ContentTypeLabel.FLV]: {
      label: ContentTypeLabel.FLV,
      is_text: false,
    },
    [ContentTypeLabel.FORTRAN]: {
      label: ContentTypeLabel.FORTRAN,
      is_text: true,
    },
    [ContentTypeLabel.FPX]: {
      label: ContentTypeLabel.FPX,
      is_text: false,
    },
    [ContentTypeLabel.GEMFILE]: {
      label: ContentTypeLabel.GEMFILE,
      is_text: true,
    },
    [ContentTypeLabel.GEMSPEC]: {
      label: ContentTypeLabel.GEMSPEC,
      is_text: true,
    },
    [ContentTypeLabel.GIF]: {
      label: ContentTypeLabel.GIF,
      is_text: false,
    },
    [ContentTypeLabel.GITATTRIBUTES]: {
      label: ContentTypeLabel.GITATTRIBUTES,
      is_text: true,
    },
    [ContentTypeLabel.GITMODULES]: {
      label: ContentTypeLabel.GITMODULES,
      is_text: true,
    },
    [ContentTypeLabel.GLEAM]: {
      label: ContentTypeLabel.GLEAM,
      is_text: true,
    },
    [ContentTypeLabel.GO]: {
      label: ContentTypeLabel.GO,
      is_text: true,
    },
    [ContentTypeLabel.GPX]: {
      label: ContentTypeLabel.GPX,
      is_text: false,
    },
    [ContentTypeLabel.GRADLE]: {
      label: ContentTypeLabel.GRADLE,
      is_text: true,
    },
    [ContentTypeLabel.GROOVY]: {
      label: ContentTypeLabel.GROOVY,
      is_text: true,
    },
    [ContentTypeLabel.GZIP]: {
      label: ContentTypeLabel.GZIP,
      is_text: false,
    },
    [ContentTypeLabel.H]: {
      label: ContentTypeLabel.H,
      is_text: true,
    },
    [ContentTypeLabel.H5]: {
      label: ContentTypeLabel.H5,
      is_text: false,
    },
    [ContentTypeLabel.HANDLEBARS]: {
      label: ContentTypeLabel.HANDLEBARS,
      is_text: true,
    },
    [ContentTypeLabel.HASKELL]: {
      label: ContentTypeLabel.HASKELL,
      is_text: true,
    },
    [ContentTypeLabel.HCL]: {
      label: ContentTypeLabel.HCL,
      is_text: true,
    },
    [ContentTypeLabel.HEIF]: {
      label: ContentTypeLabel.HEIF,
      is_text: false,
    },
    [ContentTypeLabel.HFS]: {
      label: ContentTypeLabel.HFS,
      is_text: false,
    },
    [ContentTypeLabel.HLP]: {
      label: ContentTypeLabel.HLP,
      is_text: false,
    },
    [ContentTypeLabel.HPP]: {
      label: ContentTypeLabel.HPP,
      is_text: true,
    },
    [ContentTypeLabel.HTA]: {
      label: ContentTypeLabel.HTA,
      is_text: false,
    },
    [ContentTypeLabel.HTACCESS]: {
      label: ContentTypeLabel.HTACCESS,
      is_text: true,
    },
    [ContentTypeLabel.HTML]: {
      label: ContentTypeLabel.HTML,
      is_text: true,
    },
    [ContentTypeLabel.HVE]: {
      label: ContentTypeLabel.HVE,
      is_text: false,
    },
    [ContentTypeLabel.HWP]: {
      label: ContentTypeLabel.HWP,
      is_text: false,
    },
    [ContentTypeLabel.ICC]: {
      label: ContentTypeLabel.ICC,
      is_text: false,
    },
    [ContentTypeLabel.ICNS]: {
      label: ContentTypeLabel.ICNS,
      is_text: false,
    },
    [ContentTypeLabel.ICO]: {
      label: ContentTypeLabel.ICO,
      is_text: false,
    },
    [ContentTypeLabel.ICS]: {
      label: ContentTypeLabel.ICS,
      is_text: true,
    },
    [ContentTypeLabel.IGNOREFILE]: {
      label: ContentTypeLabel.IGNOREFILE,
      is_text: true,
    },
    [ContentTypeLabel.IMG]: {
      label: ContentTypeLabel.IMG,
      is_text: false,
    },
    [ContentTypeLabel.INI]: {
      label: ContentTypeLabel.INI,
      is_text: true,
    },
    [ContentTypeLabel.INTERNETSHORTCUT]: {
      label: ContentTypeLabel.INTERNETSHORTCUT,
      is_text: true,
    },
    [ContentTypeLabel.IOSAPP]: {
      label: ContentTypeLabel.IOSAPP,
      is_text: false,
    },
    [ContentTypeLabel.IPYNB]: {
      label: ContentTypeLabel.IPYNB,
      is_text: true,
    },
    [ContentTypeLabel.ISO]: {
      label: ContentTypeLabel.ISO,
      is_text: false,
    },
    [ContentTypeLabel.JAR]: {
      label: ContentTypeLabel.JAR,
      is_text: false,
    },
    [ContentTypeLabel.JAVA]: {
      label: ContentTypeLabel.JAVA,
      is_text: true,
    },
    [ContentTypeLabel.JAVABYTECODE]: {
      label: ContentTypeLabel.JAVABYTECODE,
      is_text: false,
    },
    [ContentTypeLabel.JAVASCRIPT]: {
      label: ContentTypeLabel.JAVASCRIPT,
      is_text: true,
    },
    [ContentTypeLabel.JINJA]: {
      label: ContentTypeLabel.JINJA,
      is_text: true,
    },
    [ContentTypeLabel.JNG]: {
      label: ContentTypeLabel.JNG,
      is_text: false,
    },
    [ContentTypeLabel.JNLP]: {
      label: ContentTypeLabel.JNLP,
      is_text: true,
    },
    [ContentTypeLabel.JP2]: {
      label: ContentTypeLabel.JP2,
      is_text: false,
    },
    [ContentTypeLabel.JPEG]: {
      label: ContentTypeLabel.JPEG,
      is_text: false,
    },
    [ContentTypeLabel.JSON]: {
      label: ContentTypeLabel.JSON,
      is_text: true,
    },
    [ContentTypeLabel.JSONC]: {
      label: ContentTypeLabel.JSONC,
      is_text: false,
    },
    [ContentTypeLabel.JSONL]: {
      label: ContentTypeLabel.JSONL,
      is_text: true,
    },
    [ContentTypeLabel.JSX]: {
      label: ContentTypeLabel.JSX,
      is_text: true,
    },
    [ContentTypeLabel.JULIA]: {
      label: ContentTypeLabel.JULIA,
      is_text: true,
    },
    [ContentTypeLabel.JXL]: {
      label: ContentTypeLabel.JXL,
      is_text: false,
    },
    [ContentTypeLabel.KO]: {
      label: ContentTypeLabel.KO,
      is_text: false,
    },
    [ContentTypeLabel.KOTLIN]: {
      label: ContentTypeLabel.KOTLIN,
      is_text: true,
    },
    [ContentTypeLabel.KS]: {
      label: ContentTypeLabel.KS,
      is_text: true,
    },
    [ContentTypeLabel.LATEX]: {
      label: ContentTypeLabel.LATEX,
      is_text: true,
    },
    [ContentTypeLabel.LATEXAUX]: {
      label: ContentTypeLabel.LATEXAUX,
      is_text: false,
    },
    [ContentTypeLabel.LESS]: {
      label: ContentTypeLabel.LESS,
      is_text: false,
    },
    [ContentTypeLabel.LHA]: {
      label: ContentTypeLabel.LHA,
      is_text: false,
    },
    [ContentTypeLabel.LICENSE]: {
      label: ContentTypeLabel.LICENSE,
      is_text: true,
    },
    [ContentTypeLabel.LISP]: {
      label: ContentTypeLabel.LISP,
      is_text: true,
    },
    [ContentTypeLabel.LITCS]: {
      label: ContentTypeLabel.LITCS,
      is_text: false,
    },
    [ContentTypeLabel.LNK]: {
      label: ContentTypeLabel.LNK,
      is_text: false,
    },
    [ContentTypeLabel.LOCK]: {
      label: ContentTypeLabel.LOCK,
      is_text: true,
    },
    [ContentTypeLabel.LRZ]: {
      label: ContentTypeLabel.LRZ,
      is_text: false,
    },
    [ContentTypeLabel.LUA]: {
      label: ContentTypeLabel.LUA,
      is_text: true,
    },
    [ContentTypeLabel.LZ]: {
      label: ContentTypeLabel.LZ,
      is_text: false,
    },
    [ContentTypeLabel.LZ4]: {
      label: ContentTypeLabel.LZ4,
      is_text: false,
    },
    [ContentTypeLabel.LZX]: {
      label: ContentTypeLabel.LZX,
      is_text: false,
    },
    [ContentTypeLabel.M3U]: {
      label: ContentTypeLabel.M3U,
      is_text: true,
    },
    [ContentTypeLabel.M4]: {
      label: ContentTypeLabel.M4,
      is_text: true,
    },
    [ContentTypeLabel.MACHO]: {
      label: ContentTypeLabel.MACHO,
      is_text: false,
    },
    [ContentTypeLabel.MAFF]: {
      label: ContentTypeLabel.MAFF,
      is_text: false,
    },
    [ContentTypeLabel.MAKEFILE]: {
      label: ContentTypeLabel.MAKEFILE,
      is_text: true,
    },
    [ContentTypeLabel.MARKDOWN]: {
      label: ContentTypeLabel.MARKDOWN,
      is_text: true,
    },
    [ContentTypeLabel.MATLAB]: {
      label: ContentTypeLabel.MATLAB,
      is_text: true,
    },
    [ContentTypeLabel.MHT]: {
      label: ContentTypeLabel.MHT,
      is_text: true,
    },
    [ContentTypeLabel.MIDI]: {
      label: ContentTypeLabel.MIDI,
      is_text: false,
    },
    [ContentTypeLabel.MKV]: {
      label: ContentTypeLabel.MKV,
      is_text: false,
    },
    [ContentTypeLabel.MP2]: {
      label: ContentTypeLabel.MP2,
      is_text: false,
    },
    [ContentTypeLabel.MP3]: {
      label: ContentTypeLabel.MP3,
      is_text: false,
    },
    [ContentTypeLabel.MP4]: {
      label: ContentTypeLabel.MP4,
      is_text: false,
    },
    [ContentTypeLabel.MPEGTS]: {
      label: ContentTypeLabel.MPEGTS,
      is_text: false,
    },
    [ContentTypeLabel.MSCOMPRESS]: {
      label: ContentTypeLabel.MSCOMPRESS,
      is_text: false,
    },
    [ContentTypeLabel.MSI]: {
      label: ContentTypeLabel.MSI,
      is_text: false,
    },
    [ContentTypeLabel.MSIX]: {
      label: ContentTypeLabel.MSIX,
      is_text: false,
    },
    [ContentTypeLabel.MST]: {
      label: ContentTypeLabel.MST,
      is_text: false,
    },
    [ContentTypeLabel.MUI]: {
      label: ContentTypeLabel.MUI,
      is_text: false,
    },
    [ContentTypeLabel.MUM]: {
      label: ContentTypeLabel.MUM,
      is_text: true,
    },
    [ContentTypeLabel.MUN]: {
      label: ContentTypeLabel.MUN,
      is_text: false,
    },
    [ContentTypeLabel.NIM]: {
      label: ContentTypeLabel.NIM,
      is_text: false,
    },
    [ContentTypeLabel.NPY]: {
      label: ContentTypeLabel.NPY,
      is_text: false,
    },
    [ContentTypeLabel.NPZ]: {
      label: ContentTypeLabel.NPZ,
      is_text: false,
    },
    [ContentTypeLabel.NULL]: {
      label: ContentTypeLabel.NULL,
      is_text: false,
    },
    [ContentTypeLabel.NUPKG]: {
      label: ContentTypeLabel.NUPKG,
      is_text: false,
    },
    [ContentTypeLabel.OBJECT]: {
      label: ContentTypeLabel.OBJECT,
      is_text: false,
    },
    [ContentTypeLabel.OBJECTIVEC]: {
      label: ContentTypeLabel.OBJECTIVEC,
      is_text: true,
    },
    [ContentTypeLabel.OCAML]: {
      label: ContentTypeLabel.OCAML,
      is_text: true,
    },
    [ContentTypeLabel.OCX]: {
      label: ContentTypeLabel.OCX,
      is_text: false,
    },
    [ContentTypeLabel.ODEX]: {
      label: ContentTypeLabel.ODEX,
      is_text: false,
    },
    [ContentTypeLabel.ODIN]: {
      label: ContentTypeLabel.ODIN,
      is_text: true,
    },
    [ContentTypeLabel.ODP]: {
      label: ContentTypeLabel.ODP,
      is_text: false,
    },
    [ContentTypeLabel.ODS]: {
      label: ContentTypeLabel.ODS,
      is_text: false,
    },
    [ContentTypeLabel.ODT]: {
      label: ContentTypeLabel.ODT,
      is_text: false,
    },
    [ContentTypeLabel.OGG]: {
      label: ContentTypeLabel.OGG,
      is_text: false,
    },
    [ContentTypeLabel.OLE]: {
      label: ContentTypeLabel.OLE,
      is_text: false,
    },
    [ContentTypeLabel.ONE]: {
      label: ContentTypeLabel.ONE,
      is_text: false,
    },
    [ContentTypeLabel.ONNX]: {
      label: ContentTypeLabel.ONNX,
      is_text: false,
    },
    [ContentTypeLabel.OOXML]: {
      label: ContentTypeLabel.OOXML,
      is_text: false,
    },
    [ContentTypeLabel.OTF]: {
      label: ContentTypeLabel.OTF,
      is_text: false,
    },
    [ContentTypeLabel.OUTLOOK]: {
      label: ContentTypeLabel.OUTLOOK,
      is_text: false,
    },
    [ContentTypeLabel.PALMOS]: {
      label: ContentTypeLabel.PALMOS,
      is_text: false,
    },
    [ContentTypeLabel.PARQUET]: {
      label: ContentTypeLabel.PARQUET,
      is_text: false,
    },
    [ContentTypeLabel.PASCAL]: {
      label: ContentTypeLabel.PASCAL,
      is_text: true,
    },
    [ContentTypeLabel.PBM]: {
      label: ContentTypeLabel.PBM,
      is_text: false,
    },
    [ContentTypeLabel.PCAP]: {
      label: ContentTypeLabel.PCAP,
      is_text: false,
    },
    [ContentTypeLabel.PDB]: {
      label: ContentTypeLabel.PDB,
      is_text: false,
    },
    [ContentTypeLabel.PDF]: {
      label: ContentTypeLabel.PDF,
      is_text: false,
    },
    [ContentTypeLabel.PEBIN]: {
      label: ContentTypeLabel.PEBIN,
      is_text: false,
    },
    [ContentTypeLabel.PEM]: {
      label: ContentTypeLabel.PEM,
      is_text: true,
    },
    [ContentTypeLabel.PERL]: {
      label: ContentTypeLabel.PERL,
      is_text: true,
    },
    [ContentTypeLabel.PGP]: {
      label: ContentTypeLabel.PGP,
      is_text: false,
    },
    [ContentTypeLabel.PHP]: {
      label: ContentTypeLabel.PHP,
      is_text: true,
    },
    [ContentTypeLabel.PICKLE]: {
      label: ContentTypeLabel.PICKLE,
      is_text: false,
    },
    [ContentTypeLabel.PNG]: {
      label: ContentTypeLabel.PNG,
      is_text: false,
    },
    [ContentTypeLabel.PO]: {
      label: ContentTypeLabel.PO,
      is_text: true,
    },
    [ContentTypeLabel.POSTSCRIPT]: {
      label: ContentTypeLabel.POSTSCRIPT,
      is_text: false,
    },
    [ContentTypeLabel.POWERSHELL]: {
      label: ContentTypeLabel.POWERSHELL,
      is_text: true,
    },
    [ContentTypeLabel.PPT]: {
      label: ContentTypeLabel.PPT,
      is_text: false,
    },
    [ContentTypeLabel.PPTX]: {
      label: ContentTypeLabel.PPTX,
      is_text: false,
    },
    [ContentTypeLabel.PRINTFOX]: {
      label: ContentTypeLabel.PRINTFOX,
      is_text: false,
    },
    [ContentTypeLabel.PROLOG]: {
      label: ContentTypeLabel.PROLOG,
      is_text: true,
    },
    [ContentTypeLabel.PROTEINDB]: {
      label: ContentTypeLabel.PROTEINDB,
      is_text: true,
    },
    [ContentTypeLabel.PROTO]: {
      label: ContentTypeLabel.PROTO,
      is_text: true,
    },
    [ContentTypeLabel.PROTOBUF]: {
      label: ContentTypeLabel.PROTOBUF,
      is_text: false,
    },
    [ContentTypeLabel.PSD]: {
      label: ContentTypeLabel.PSD,
      is_text: false,
    },
    [ContentTypeLabel.PUB]: {
      label: ContentTypeLabel.PUB,
      is_text: false,
    },
    [ContentTypeLabel.PYTHON]: {
      label: ContentTypeLabel.PYTHON,
      is_text: true,
    },
    [ContentTypeLabel.PYTHONBYTECODE]: {
      label: ContentTypeLabel.PYTHONBYTECODE,
      is_text: false,
    },
    [ContentTypeLabel.PYTHONPAR]: {
      label: ContentTypeLabel.PYTHONPAR,
      is_text: false,
    },
    [ContentTypeLabel.PYTORCH]: {
      label: ContentTypeLabel.PYTORCH,
      is_text: false,
    },
    [ContentTypeLabel.QOI]: {
      label: ContentTypeLabel.QOI,
      is_text: false,
    },
    [ContentTypeLabel.QT]: {
      label: ContentTypeLabel.QT,
      is_text: false,
    },
    [ContentTypeLabel.R]: {
      label: ContentTypeLabel.R,
      is_text: true,
    },
    [ContentTypeLabel.RANDOMASCII]: {
      label: ContentTypeLabel.RANDOMASCII,
      is_text: true,
    },
    [ContentTypeLabel.RANDOMBYTES]: {
      label: ContentTypeLabel.RANDOMBYTES,
      is_text: false,
    },
    [ContentTypeLabel.RANDOMTXT]: {
      label: ContentTypeLabel.RANDOMTXT,
      is_text: true,
    },
    [ContentTypeLabel.RAR]: {
      label: ContentTypeLabel.RAR,
      is_text: false,
    },
    [ContentTypeLabel.RDF]: {
      label: ContentTypeLabel.RDF,
      is_text: true,
    },
    [ContentTypeLabel.RDP]: {
      label: ContentTypeLabel.RDP,
      is_text: false,
    },
    [ContentTypeLabel.RIFF]: {
      label: ContentTypeLabel.RIFF,
      is_text: false,
    },
    [ContentTypeLabel.RLIB]: {
      label: ContentTypeLabel.RLIB,
      is_text: false,
    },
    [ContentTypeLabel.RLL]: {
      label: ContentTypeLabel.RLL,
      is_text: false,
    },
    [ContentTypeLabel.RPM]: {
      label: ContentTypeLabel.RPM,
      is_text: false,
    },
    [ContentTypeLabel.RST]: {
      label: ContentTypeLabel.RST,
      is_text: true,
    },
    [ContentTypeLabel.RTF]: {
      label: ContentTypeLabel.RTF,
      is_text: true,
    },
    [ContentTypeLabel.RUBY]: {
      label: ContentTypeLabel.RUBY,
      is_text: true,
    },
    [ContentTypeLabel.RUST]: {
      label: ContentTypeLabel.RUST,
      is_text: true,
    },
    [ContentTypeLabel.RZIP]: {
      label: ContentTypeLabel.RZIP,
      is_text: false,
    },
    [ContentTypeLabel.SCALA]: {
      label: ContentTypeLabel.SCALA,
      is_text: true,
    },
    [ContentTypeLabel.SCHEME]: {
      label: ContentTypeLabel.SCHEME,
      is_text: false,
    },
    [ContentTypeLabel.SCR]: {
      label: ContentTypeLabel.SCR,
      is_text: false,
    },
    [ContentTypeLabel.SCRIPTWSF]: {
      label: ContentTypeLabel.SCRIPTWSF,
      is_text: false,
    },
    [ContentTypeLabel.SCSS]: {
      label: ContentTypeLabel.SCSS,
      is_text: true,
    },
    [ContentTypeLabel.SEVENZIP]: {
      label: ContentTypeLabel.SEVENZIP,
      is_text: false,
    },
    [ContentTypeLabel.SGML]: {
      label: ContentTypeLabel.SGML,
      is_text: true,
    },
    [ContentTypeLabel.SH3D]: {
      label: ContentTypeLabel.SH3D,
      is_text: false,
    },
    [ContentTypeLabel.SHELL]: {
      label: ContentTypeLabel.SHELL,
      is_text: true,
    },
    [ContentTypeLabel.SMALI]: {
      label: ContentTypeLabel.SMALI,
      is_text: true,
    },
    [ContentTypeLabel.SNAP]: {
      label: ContentTypeLabel.SNAP,
      is_text: false,
    },
    [ContentTypeLabel.SO]: {
      label: ContentTypeLabel.SO,
      is_text: false,
    },
    [ContentTypeLabel.SOLIDITY]: {
      label: ContentTypeLabel.SOLIDITY,
      is_text: true,
    },
    [ContentTypeLabel.SQL]: {
      label: ContentTypeLabel.SQL,
      is_text: true,
    },
    [ContentTypeLabel.SQLITE]: {
      label: ContentTypeLabel.SQLITE,
      is_text: false,
    },
    [ContentTypeLabel.SQUASHFS]: {
      label: ContentTypeLabel.SQUASHFS,
      is_text: false,
    },
    [ContentTypeLabel.SRT]: {
      label: ContentTypeLabel.SRT,
      is_text: true,
    },
    [ContentTypeLabel.STLBINARY]: {
      label: ContentTypeLabel.STLBINARY,
      is_text: false,
    },
    [ContentTypeLabel.STLTEXT]: {
      label: ContentTypeLabel.STLTEXT,
      is_text: true,
    },
    [ContentTypeLabel.SUM]: {
      label: ContentTypeLabel.SUM,
      is_text: true,
    },
    [ContentTypeLabel.SVD]: {
      label: ContentTypeLabel.SVD,
      is_text: false,
    },
    [ContentTypeLabel.SVG]: {
      label: ContentTypeLabel.SVG,
      is_text: true,
    },
    [ContentTypeLabel.SWF]: {
      label: ContentTypeLabel.SWF,
      is_text: false,
    },
    [ContentTypeLabel.SWIFT]: {
      label: ContentTypeLabel.SWIFT,
      is_text: true,
    },
    [ContentTypeLabel.SYMLINK]: {
      label: ContentTypeLabel.SYMLINK,
      is_text: false,
    },
    [ContentTypeLabel.SYMLINKTEXT]: {
      label: ContentTypeLabel.SYMLINKTEXT,
      is_text: true,
    },
    [ContentTypeLabel.SYS]: {
      label: ContentTypeLabel.SYS,
      is_text: false,
    },
    [ContentTypeLabel.TAR]: {
      label: ContentTypeLabel.TAR,
      is_text: false,
    },
    [ContentTypeLabel.TCL]: {
      label: ContentTypeLabel.TCL,
      is_text: true,
    },
    [ContentTypeLabel.TEXTPROTO]: {
      label: ContentTypeLabel.TEXTPROTO,
      is_text: true,
    },
    [ContentTypeLabel.TGA]: {
      label: ContentTypeLabel.TGA,
      is_text: false,
    },
    [ContentTypeLabel.THUMBSDB]: {
      label: ContentTypeLabel.THUMBSDB,
      is_text: false,
    },
    [ContentTypeLabel.TIFF]: {
      label: ContentTypeLabel.TIFF,
      is_text: false,
    },
    [ContentTypeLabel.TMDX]: {
      label: ContentTypeLabel.TMDX,
      is_text: false,
    },
    [ContentTypeLabel.TOML]: {
      label: ContentTypeLabel.TOML,
      is_text: true,
    },
    [ContentTypeLabel.TORRENT]: {
      label: ContentTypeLabel.TORRENT,
      is_text: false,
    },
    [ContentTypeLabel.TROFF]: {
      label: ContentTypeLabel.TROFF,
      is_text: false,
    },
    [ContentTypeLabel.TSV]: {
      label: ContentTypeLabel.TSV,
      is_text: true,
    },
    [ContentTypeLabel.TSX]: {
      label: ContentTypeLabel.TSX,
      is_text: true,
    },
    [ContentTypeLabel.TTF]: {
      label: ContentTypeLabel.TTF,
      is_text: false,
    },
    [ContentTypeLabel.TWIG]: {
      label: ContentTypeLabel.TWIG,
      is_text: true,
    },
    [ContentTypeLabel.TXT]: {
      label: ContentTypeLabel.TXT,
      is_text: true,
    },
    [ContentTypeLabel.TXTASCII]: {
      label: ContentTypeLabel.TXTASCII,
      is_text: true,
    },
    [ContentTypeLabel.TXTUTF16]: {
      label: ContentTypeLabel.TXTUTF16,
      is_text: true,
    },
    [ContentTypeLabel.TXTUTF8]: {
      label: ContentTypeLabel.TXTUTF8,
      is_text: true,
    },
    [ContentTypeLabel.TYPESCRIPT]: {
      label: ContentTypeLabel.TYPESCRIPT,
      is_text: true,
    },
    [ContentTypeLabel.UDF]: {
      label: ContentTypeLabel.UDF,
      is_text: false,
    },
    [ContentTypeLabel.UNDEFINED]: {
      label: ContentTypeLabel.UNDEFINED,
      is_text: false,
    },
    [ContentTypeLabel.UNIXCOMPRESS]: {
      label: ContentTypeLabel.UNIXCOMPRESS,
      is_text: false,
    },
    [ContentTypeLabel.UNKNOWN]: {
      label: ContentTypeLabel.UNKNOWN,
      is_text: false,
    },
    [ContentTypeLabel.VBA]: {
      label: ContentTypeLabel.VBA,
      is_text: true,
    },
    [ContentTypeLabel.VBE]: {
      label: ContentTypeLabel.VBE,
      is_text: false,
    },
    [ContentTypeLabel.VCARD]: {
      label: ContentTypeLabel.VCARD,
      is_text: false,
    },
    [ContentTypeLabel.VCS]: {
      label: ContentTypeLabel.VCS,
      is_text: false,
    },
    [ContentTypeLabel.VCXPROJ]: {
      label: ContentTypeLabel.VCXPROJ,
      is_text: true,
    },
    [ContentTypeLabel.VERILOG]: {
      label: ContentTypeLabel.VERILOG,
      is_text: true,
    },
    [ContentTypeLabel.VHD]: {
      label: ContentTypeLabel.VHD,
      is_text: false,
    },
    [ContentTypeLabel.VHDL]: {
      label: ContentTypeLabel.VHDL,
      is_text: true,
    },
    [ContentTypeLabel.VISIO]: {
      label: ContentTypeLabel.VISIO,
      is_text: false,
    },
    [ContentTypeLabel.VTT]: {
      label: ContentTypeLabel.VTT,
      is_text: true,
    },
    [ContentTypeLabel.VUE]: {
      label: ContentTypeLabel.VUE,
      is_text: true,
    },
    [ContentTypeLabel.WAD]: {
      label: ContentTypeLabel.WAD,
      is_text: false,
    },
    [ContentTypeLabel.WASM]: {
      label: ContentTypeLabel.WASM,
      is_text: false,
    },
    [ContentTypeLabel.WAV]: {
      label: ContentTypeLabel.WAV,
      is_text: false,
    },
    [ContentTypeLabel.WEBM]: {
      label: ContentTypeLabel.WEBM,
      is_text: false,
    },
    [ContentTypeLabel.WEBP]: {
      label: ContentTypeLabel.WEBP,
      is_text: false,
    },
    [ContentTypeLabel.WEBTEMPLATE]: {
      label: ContentTypeLabel.WEBTEMPLATE,
      is_text: true,
    },
    [ContentTypeLabel.WIM]: {
      label: ContentTypeLabel.WIM,
      is_text: false,
    },
    [ContentTypeLabel.WINREGISTRY]: {
      label: ContentTypeLabel.WINREGISTRY,
      is_text: true,
    },
    [ContentTypeLabel.WMA]: {
      label: ContentTypeLabel.WMA,
      is_text: false,
    },
    [ContentTypeLabel.WMF]: {
      label: ContentTypeLabel.WMF,
      is_text: false,
    },
    [ContentTypeLabel.WMV]: {
      label: ContentTypeLabel.WMV,
      is_text: false,
    },
    [ContentTypeLabel.WOFF]: {
      label: ContentTypeLabel.WOFF,
      is_text: false,
    },
    [ContentTypeLabel.WOFF2]: {
      label: ContentTypeLabel.WOFF2,
      is_text: false,
    },
    [ContentTypeLabel.XAR]: {
      label: ContentTypeLabel.XAR,
      is_text: false,
    },
    [ContentTypeLabel.XCF]: {
      label: ContentTypeLabel.XCF,
      is_text: false,
    },
    [ContentTypeLabel.XLS]: {
      label: ContentTypeLabel.XLS,
      is_text: false,
    },
    [ContentTypeLabel.XLSB]: {
      label: ContentTypeLabel.XLSB,
      is_text: false,
    },
    [ContentTypeLabel.XLSX]: {
      label: ContentTypeLabel.XLSX,
      is_text: false,
    },
    [ContentTypeLabel.XML]: {
      label: ContentTypeLabel.XML,
      is_text: true,
    },
    [ContentTypeLabel.XPI]: {
      label: ContentTypeLabel.XPI,
      is_text: false,
    },
    [ContentTypeLabel.XSD]: {
      label: ContentTypeLabel.XSD,
      is_text: false,
    },
    [ContentTypeLabel.XZ]: {
      label: ContentTypeLabel.XZ,
      is_text: false,
    },
    [ContentTypeLabel.YAML]: {
      label: ContentTypeLabel.YAML,
      is_text: true,
    },
    [ContentTypeLabel.YARA]: {
      label: ContentTypeLabel.YARA,
      is_text: true,
    },
    [ContentTypeLabel.ZIG]: {
      label: ContentTypeLabel.ZIG,
      is_text: true,
    },
    [ContentTypeLabel.ZIP]: {
      label: ContentTypeLabel.ZIP,
      is_text: false,
    },
    [ContentTypeLabel.ZLIBSTREAM]: {
      label: ContentTypeLabel.ZLIBSTREAM,
      is_text: false,
    },
    [ContentTypeLabel.ZST]: {
      label: ContentTypeLabel.ZST,
      is_text: false,
    },
  }),
};
