# Scorecard maintainer annotations.
# See https://github.com/ossf/scorecard/blob/main/config/README.md

annotations:

  # Binary files in tests_data/ are only used for testing.
  - checks:
      - binary-artifacts
    reasons:
      - reason: test-data 

  - checks:
      - pinned-dependencies
    reasons:
      # Test data with unpinned dependencies:
      # - tests_data/basic/dockerfile/Dockerfile
      - reason: test-data
      # CI/CD containers meant to run the latest version:
      # - .github/workflows/python-e2e-test.yml
      - reason: remediated
