// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::output::Metadata;

/// Content type of a file.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum Label {
    /// Adobe Illustrator Artwork
    Ai,
    /// Android package
    Apk,
    /// Apple property list
    Appleplist,
    /// Assembly
    Asm,
    /// ASP source
    Asp,
    /// DOS batch file
    Batch,
    /// BMP image data
    Bmp,
    /// bzip2 compressed data
    Bzip,
    /// C source
    C,
    /// Microsoft Cabinet archive data
    Cab,
    /// Windows Catalog file
    Cat,
    /// MS Windows HtmlHelp Data
    Chm,
    /// Intel 80386 COFF
    Coff,
    /// Google Chrome extension
    Crx,
    /// C# source
    Cs,
    /// CSS source
    Css,
    /// CSV document
    Csv,
    /// Debian binary package
    Deb,
    /// Dalvik dex file
    Dex,
    /// Apple disk image
    Dmg,
    /// Microsoft Word CDF document
    Doc,
    /// Microsoft Word 2007+ document
    Docx,
    /// ELF executable
    Elf,
    /// Windows Enhanced Metafile image data
    Emf,
    /// RFC 822 mail
    Eml,
    /// EPUB document
    Epub,
    /// FLAC audio bitstream data
    Flac,
    /// GIF image data
    Gif,
    /// Golang source
    Go,
    /// gzip compressed data
    Gzip,
    /// MS Windows help
    Hlp,
    /// HTML document
    Html,
    /// MS Windows icon resource
    Ico,
    /// INI configuration file
    Ini,
    /// MS Windows Internet shortcut
    Internetshortcut,
    /// ISO 9660 CD-ROM filesystem data
    Iso,
    /// Java archive data (JAR)
    Jar,
    /// Java source
    Java,
    /// Java compiled bytecode
    Javabytecode,
    /// JavaScript source
    Javascript,
    /// JPEG image data
    Jpeg,
    /// JSON document
    Json,
    /// LaTeX document
    Latex,
    /// Lisp source
    Lisp,
    /// MS Windows shortcut
    Lnk,
    /// M3U playlist
    M3u,
    /// Mach-O executable
    Macho,
    /// Makefile source
    Makefile,
    /// Markdown document
    Markdown,
    /// MHTML document
    Mht,
    /// MP3 media file
    Mp3,
    /// MP4 media file
    Mp4,
    /// MS Compress archive data
    Mscompress,
    /// Microsoft Installer file
    Msi,
    /// Windows Update Package file
    Mum,
    /// ODEX ELF executable
    Odex,
    /// OpenDocument Presentation
    Odp,
    /// OpenDocument Spreadsheet
    Ods,
    /// OpenDocument Text
    Odt,
    /// Ogg data
    Ogg,
    /// MS Outlook Message
    Outlook,
    /// pcap capture file
    Pcap,
    /// PDF document
    Pdf,
    /// ELF executable | PE Windows executable
    Pebin,
    /// PEM certificate
    Pem,
    /// Perl source
    Perl,
    /// PHP source
    Php,
    /// PNG image data
    Png,
    /// PostScript document
    Postscript,
    /// Powershell source
    Powershell,
    /// Microsoft PowerPoint CDF document
    Ppt,
    /// Microsoft PowerPoint 2007+ document
    Pptx,
    /// Python source
    Python,
    /// Python compiled bytecode
    Pythonbytecode,
    /// RAR archive data
    Rar,
    /// Resource Description Framework document (RDF)
    Rdf,
    /// RedHat Package Manager archive (RPM)
    Rpm,
    /// ReStructuredText document
    Rst,
    /// Rich Text Format document
    Rtf,
    /// Ruby source
    Ruby,
    /// Rust source
    Rust,
    /// Scala source
    Scala,
    /// 7-zip archive data
    Sevenzip,
    /// Shell script
    Shell,
    /// Smali source
    Smali,
    /// SQL source
    Sql,
    /// Squash filesystem
    Squashfs,
    /// SVG Scalable Vector Graphics image data
    Svg,
    /// Macromedia Flash data
    Swf,
    /// Symbolic link (textual representation)
    Symlinktext,
    /// POSIX tar archive
    Tar,
    /// Targa image data
    Tga,
    /// TIFF image data
    Tiff,
    /// BitTorrent file
    Torrent,
    /// TrueType Font data
    Ttf,
    /// Generic text document
    Txt,
    /// Unknown binary data
    Unknown,
    /// MS Visual Basic source (VBA)
    Vba,
    /// Waveform Audio file (WAV)
    Wav,
    /// WebM data
    Webm,
    /// WebP data
    Webp,
    /// Windows Registry text
    Winregistry,
    /// Windows metafile
    Wmf,
    /// XAR archive compressed data
    Xar,
    /// Microsoft Excel CDF document
    Xls,
    /// Microsoft Excel 2007+ document (binary format)
    Xlsb,
    /// Microsoft Excel 2007+ document
    Xlsx,
    /// XML document
    Xml,
    /// Compressed installation archive (XPI)
    Xpi,
    /// XZ compressed data
    Xz,
    /// YAML source
    Yaml,
    /// Zip archive data
    Zip,
    /// zlib compressed data
    Zlibstream,
}

pub(crate) const MAX_LABEL: u32 = 112;

pub(crate) const METADATA: [Metadata; 113] = [
    Metadata {
        code: "ai",
        short: "ai",
        long: "Adobe Illustrator Artwork",
        magic: "PDF document",
        group: "document",
        mime: "application/pdf",
        text: false,
    },
    Metadata {
        code: "apk",
        short: "apk",
        long: "Android package",
        magic: "Java archive data",
        group: "executable",
        mime: "application/vnd.android.package-archive",
        text: false,
    },
    Metadata {
        code: "appleplist",
        short: "appleplist",
        long: "Apple property list",
        magic: "Apple binary property list",
        group: "application",
        mime: "application/x-plist",
        text: true,
    },
    Metadata {
        code: "asm",
        short: "asm",
        long: "Assembly",
        magic: "assembler source",
        group: "code",
        mime: "text/x-asm",
        text: true,
    },
    Metadata {
        code: "asp",
        short: "asp",
        long: "ASP source",
        magic: "HTML document",
        group: "code",
        mime: "text/html",
        text: true,
    },
    Metadata {
        code: "batch",
        short: "batch",
        long: "DOS batch file",
        magic: "DOS batch file",
        group: "code",
        mime: "text/x-msdos-batch",
        text: true,
    },
    Metadata {
        code: "bmp",
        short: "bmp",
        long: "BMP image data",
        magic: "PC bitmap",
        group: "image",
        mime: "image/bmp",
        text: false,
    },
    Metadata {
        code: "bzip",
        short: "bzip",
        long: "bzip2 compressed data",
        magic: "bzip2 compressed data",
        group: "archive",
        mime: "application/x-bzip2",
        text: false,
    },
    Metadata {
        code: "c",
        short: "c",
        long: "C source",
        magic: "C source",
        group: "code",
        mime: "text/x-c",
        text: true,
    },
    Metadata {
        code: "cab",
        short: "cab",
        long: "Microsoft Cabinet archive data",
        magic: "Microsoft Cabinet archive data",
        group: "archive",
        mime: "application/vnd.ms-cab-compressed",
        text: false,
    },
    Metadata {
        code: "cat",
        short: "cat",
        long: "Windows Catalog file",
        magic: "data",
        group: "application",
        mime: "application/octet-stream",
        text: false,
    },
    Metadata {
        code: "chm",
        short: "chm",
        long: "MS Windows HtmlHelp Data",
        magic: "MS Windows HtmlHelp Data",
        group: "application",
        mime: "application/chm",
        text: false,
    },
    Metadata {
        code: "coff",
        short: "coff",
        long: "Intel 80386 COFF",
        magic: "Intel 80386 COFF",
        group: "executable",
        mime: "application/x-coff",
        text: false,
    },
    Metadata {
        code: "crx",
        short: "crx",
        long: "Google Chrome extension",
        magic: "Google Chrome extension",
        group: "executable",
        mime: "application/x-chrome-extension",
        text: false,
    },
    Metadata {
        code: "cs",
        short: "cs",
        long: "C# source",
        magic: "ASCII text",
        group: "code",
        mime: "text/plain",
        text: true,
    },
    Metadata {
        code: "css",
        short: "css",
        long: "CSS source",
        magic: "ASCII text",
        group: "code",
        mime: "text/css",
        text: true,
    },
    Metadata {
        code: "csv",
        short: "csv",
        long: "CSV document",
        magic: "CSV text",
        group: "code",
        mime: "text/csv",
        text: true,
    },
    Metadata {
        code: "deb",
        short: "deb",
        long: "Debian binary package",
        magic: "Debian binary package",
        group: "archive",
        mime: "application/vnd.debian.binary-package",
        text: false,
    },
    Metadata {
        code: "dex",
        short: "dex",
        long: "Dalvik dex file",
        magic: "Dalvik dex file",
        group: "executable",
        mime: "application/x-android-dex",
        text: false,
    },
    Metadata {
        code: "dmg",
        short: "dmg",
        long: "Apple disk image",
        magic: "Apple disk image",
        group: "archive",
        mime: "application/x-apple-diskimage",
        text: false,
    },
    Metadata {
        code: "doc",
        short: "doc",
        long: "Microsoft Word CDF document",
        magic: "Composite Document File",
        group: "document",
        mime: "application/msword",
        text: false,
    },
    Metadata {
        code: "docx",
        short: "docx",
        long: "Microsoft Word 2007+ document",
        magic: "Microsoft Word 2007+",
        group: "document",
        mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        text: false,
    },
    Metadata {
        code: "elf",
        short: "elf | ko | so",
        long: "ELF executable",
        magic: "ELF executable",
        group: "executable",
        mime: "application/x-executable-elf",
        text: false,
    },
    Metadata {
        code: "emf",
        short: "emf",
        long: "Windows Enhanced Metafile image data",
        magic: "Windows Enhanced Metafile",
        group: "application",
        mime: "application/octet-stream",
        text: false,
    },
    Metadata {
        code: "eml",
        short: "eml",
        long: "RFC 822 mail",
        magic: "RFC 822 mail",
        group: "text",
        mime: "message/rfc822",
        text: true,
    },
    Metadata {
        code: "epub",
        short: "epub",
        long: "EPUB document",
        magic: "EPUB document",
        group: "document",
        mime: "application/epub+zip",
        text: false,
    },
    Metadata {
        code: "flac",
        short: "flac",
        long: "FLAC audio bitstream data",
        magic: "FLAC audio bitstream data",
        group: "audio",
        mime: "audio/flac",
        text: false,
    },
    Metadata {
        code: "gif",
        short: "gif",
        long: "GIF image data",
        magic: "GIF image data",
        group: "image",
        mime: "image/gif",
        text: false,
    },
    Metadata {
        code: "go",
        short: "go",
        long: "Golang source",
        magic: "ASCII text",
        group: "code",
        mime: "text/x-golang",
        text: true,
    },
    Metadata {
        code: "gzip",
        short: "gzip",
        long: "gzip compressed data",
        magic: "gzip compressed data",
        group: "archive",
        mime: "application/gzip",
        text: false,
    },
    Metadata {
        code: "hlp",
        short: "hlp",
        long: "MS Windows help",
        magic: "MS Windows help",
        group: "application",
        mime: "application/winhlp",
        text: false,
    },
    Metadata {
        code: "html",
        short: "html",
        long: "HTML document",
        magic: "HTML document",
        group: "code",
        mime: "text/html",
        text: true,
    },
    Metadata {
        code: "ico",
        short: "ico",
        long: "MS Windows icon resource",
        magic: "MS Windows icon resource",
        group: "image",
        mime: "image/vnd.microsoft.icon",
        text: false,
    },
    Metadata {
        code: "ini",
        short: "ini",
        long: "INI configuration file",
        magic: "Generic INItialization configuration",
        group: "text",
        mime: "text/plain",
        text: true,
    },
    Metadata {
        code: "internetshortcut",
        short: "internetshortcut",
        long: "MS Windows Internet shortcut",
        magic: "MS Windows 95 Internet shortcut",
        group: "application",
        mime: "application/x-mswinurl",
        text: true,
    },
    Metadata {
        code: "iso",
        short: "iso",
        long: "ISO 9660 CD-ROM filesystem data",
        magic: "ISO 9660 CD-ROM filesystem data",
        group: "archive",
        mime: "application/x-iso9660-image",
        text: false,
    },
    Metadata {
        code: "jar",
        short: "jar",
        long: "Java archive data (JAR)",
        magic: "Java archive data (JAR)",
        group: "archive",
        mime: "application/java-archive",
        text: false,
    },
    Metadata {
        code: "java",
        short: "java",
        long: "Java source",
        magic: "Java source",
        group: "code",
        mime: "text/x-java",
        text: true,
    },
    Metadata {
        code: "javabytecode",
        short: "javabytecode",
        long: "Java compiled bytecode",
        magic: "compiled Java class data",
        group: "executable",
        mime: "application/x-java-applet",
        text: false,
    },
    Metadata {
        code: "javascript",
        short: "javascript",
        long: "JavaScript source",
        magic: "JavaScript source",
        group: "code",
        mime: "application/javascript",
        text: true,
    },
    Metadata {
        code: "jpeg",
        short: "jpeg",
        long: "JPEG image data",
        magic: "JPEG image data",
        group: "image",
        mime: "image/jpeg",
        text: false,
    },
    Metadata {
        code: "json",
        short: "json",
        long: "JSON document",
        magic: "JSON data",
        group: "code",
        mime: "application/json",
        text: true,
    },
    Metadata {
        code: "latex",
        short: "latex",
        long: "LaTeX document",
        magic: "LaTeX document",
        group: "text",
        mime: "text/x-tex",
        text: true,
    },
    Metadata {
        code: "lisp",
        short: "lisp",
        long: "Lisp source",
        magic: "Lisp/Scheme program",
        group: "code",
        mime: "text/x-lisp",
        text: true,
    },
    Metadata {
        code: "lnk",
        short: "lnk",
        long: "MS Windows shortcut",
        magic: "MS Windows shortcut",
        group: "application",
        mime: "application/x-ms-shortcut",
        text: false,
    },
    Metadata {
        code: "m3u",
        short: "m3u",
        long: "M3U playlist",
        magic: "M3U playlist",
        group: "application",
        mime: "text/plain",
        text: false,
    },
    Metadata {
        code: "macho",
        short: "dylib | macho",
        long: "Mach-O executable",
        magic: "Mach-O executable",
        group: "executable",
        mime: "application/x-mach-o",
        text: false,
    },
    Metadata {
        code: "makefile",
        short: "makefile",
        long: "Makefile source",
        magic: "makefile script",
        group: "code",
        mime: "text/x-makefile",
        text: true,
    },
    Metadata {
        code: "markdown",
        short: "markdown",
        long: "Markdown document",
        magic: "ASCII text",
        group: "text",
        mime: "text/markdown",
        text: true,
    },
    Metadata {
        code: "mht",
        short: "mht",
        long: "MHTML document",
        magic: "HTML document",
        group: "code",
        mime: "application/x-mimearchive",
        text: true,
    },
    Metadata {
        code: "mp3",
        short: "mp3",
        long: "MP3 media file",
        magic: "Audio file with ID3",
        group: "audio",
        mime: "audio/mpeg",
        text: false,
    },
    Metadata {
        code: "mp4",
        short: "mp4",
        long: "MP4 media file",
        magic: "ISO Media",
        group: "video",
        mime: "video/mp4",
        text: false,
    },
    Metadata {
        code: "mscompress",
        short: "mscompress",
        long: "MS Compress archive data",
        magic: "MS Compress archive data",
        group: "archive",
        mime: "application/x-ms-compress-szdd",
        text: false,
    },
    Metadata {
        code: "msi",
        short: "msi",
        long: "Microsoft Installer file",
        magic: "Composite Document File",
        group: "archive",
        mime: "application/x-msi",
        text: false,
    },
    Metadata {
        code: "mum",
        short: "mum",
        long: "Windows Update Package file",
        magic: "XML document",
        group: "application",
        mime: "text/xml",
        text: true,
    },
    Metadata {
        code: "odex",
        short: "odex",
        long: "ODEX ELF executable",
        magic: "ELF executable",
        group: "executable",
        mime: "application/x-executable-elf",
        text: false,
    },
    Metadata {
        code: "odp",
        short: "odp",
        long: "OpenDocument Presentation",
        magic: "OpenDocument Presentation",
        group: "document",
        mime: "application/vnd.oasis.opendocument.presentation",
        text: false,
    },
    Metadata {
        code: "ods",
        short: "ods",
        long: "OpenDocument Spreadsheet",
        magic: "OpenDocument Spreadsheet",
        group: "document",
        mime: "application/vnd.oasis.opendocument.spreadsheet",
        text: false,
    },
    Metadata {
        code: "odt",
        short: "odt",
        long: "OpenDocument Text",
        magic: "OpenDocument Text",
        group: "document",
        mime: "application/vnd.oasis.opendocument.text",
        text: false,
    },
    Metadata {
        code: "ogg",
        short: "ogg",
        long: "Ogg data",
        magic: "Ogg data",
        group: "audio",
        mime: "audio/ogg",
        text: false,
    },
    Metadata {
        code: "outlook",
        short: "outlook",
        long: "MS Outlook Message",
        magic: "CDFV2 Microsoft Outlook Message",
        group: "application",
        mime: "application/vnd.ms-outlook",
        text: false,
    },
    Metadata {
        code: "pcap",
        short: "pcap",
        long: "pcap capture file",
        magic: "pcap capture file",
        group: "application",
        mime: "application/vnd.tcpdump.pcap",
        text: false,
    },
    Metadata {
        code: "pdf",
        short: "pdf",
        long: "PDF document",
        magic: "PDF document",
        group: "document",
        mime: "application/pdf",
        text: false,
    },
    Metadata {
        code: "pebin",
        short: "cpl | dll | exe | mui | ocx | scr | sys",
        long: "ELF executable | PE Windows executable",
        magic: "ELF executable | PE Windows executable | PE32 executable",
        group: "application | executable",
        mime: "application/x-dosexec | application/x-windows-driver",
        text: false,
    },
    Metadata {
        code: "pem",
        short: "pem",
        long: "PEM certificate",
        magic: "PEM certificate",
        group: "application",
        mime: "application/x-pem-file",
        text: true,
    },
    Metadata {
        code: "perl",
        short: "perl",
        long: "Perl source",
        magic: "Perl script text executable",
        group: "code",
        mime: "text/x-perl",
        text: true,
    },
    Metadata {
        code: "php",
        short: "php",
        long: "PHP source",
        magic: "PHP script",
        group: "code",
        mime: "text/x-php",
        text: true,
    },
    Metadata {
        code: "png",
        short: "png",
        long: "PNG image data",
        magic: "PNG image data",
        group: "image",
        mime: "image/png",
        text: false,
    },
    Metadata {
        code: "postscript",
        short: "postscript",
        long: "PostScript document",
        magic: "PostScript document text",
        group: "document",
        mime: "application/postscript",
        text: false,
    },
    Metadata {
        code: "powershell",
        short: "powershell",
        long: "Powershell source",
        magic: "a powershell script",
        group: "code",
        mime: "application/x-powershell",
        text: true,
    },
    Metadata {
        code: "ppt",
        short: "ppt",
        long: "Microsoft PowerPoint CDF document",
        magic: "Composite Document File",
        group: "document",
        mime: "application/vnd.ms-powerpoint",
        text: false,
    },
    Metadata {
        code: "pptx",
        short: "pptx",
        long: "Microsoft PowerPoint 2007+ document",
        magic: "Microsoft PowerPoint 2007+",
        group: "document",
        mime: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        text: false,
    },
    Metadata {
        code: "python",
        short: "python",
        long: "Python source",
        magic: "Python script",
        group: "code",
        mime: "text/x-python",
        text: true,
    },
    Metadata {
        code: "pythonbytecode",
        short: "pythonbytecode",
        long: "Python compiled bytecode",
        magic: "python byte-compiled",
        group: "executable",
        mime: "application/x-bytecode.python",
        text: false,
    },
    Metadata {
        code: "rar",
        short: "rar",
        long: "RAR archive data",
        magic: "RAR archive data",
        group: "archive",
        mime: "application/x-rar",
        text: false,
    },
    Metadata {
        code: "rdf",
        short: "rdf",
        long: "Resource Description Framework document (RDF)",
        magic: "XML document",
        group: "text",
        mime: "application/rdf+xml",
        text: true,
    },
    Metadata {
        code: "rpm",
        short: "rpm",
        long: "RedHat Package Manager archive (RPM)",
        magic: "RPM",
        group: "archive",
        mime: "application/x-rpm",
        text: false,
    },
    Metadata {
        code: "rst",
        short: "rst",
        long: "ReStructuredText document",
        magic: "ReStructuredText file",
        group: "text",
        mime: "text/x-rst",
        text: true,
    },
    Metadata {
        code: "rtf",
        short: "rtf",
        long: "Rich Text Format document",
        magic: "Rich Text Format data",
        group: "text",
        mime: "text/rtf",
        text: true,
    },
    Metadata {
        code: "ruby",
        short: "ruby",
        long: "Ruby source",
        magic: "Ruby script",
        group: "code",
        mime: "application/x-ruby",
        text: true,
    },
    Metadata {
        code: "rust",
        short: "rust",
        long: "Rust source",
        magic: "ASCII text",
        group: "code",
        mime: "application/x-rust",
        text: true,
    },
    Metadata {
        code: "scala",
        short: "scala",
        long: "Scala source",
        magic: "ASCII text",
        group: "code",
        mime: "application/x-scala",
        text: true,
    },
    Metadata {
        code: "sevenzip",
        short: "sevenzip",
        long: "7-zip archive data",
        magic: "7-zip archive data",
        group: "archive",
        mime: "application/x-7z-compressed",
        text: false,
    },
    Metadata {
        code: "shell",
        short: "shell",
        long: "Shell script",
        magic: "shell script",
        group: "code",
        mime: "text/x-shellscript",
        text: true,
    },
    Metadata {
        code: "smali",
        short: "smali",
        long: "Smali source",
        magic: "ASCII text",
        group: "code",
        mime: "application/x-smali",
        text: true,
    },
    Metadata {
        code: "sql",
        short: "sql",
        long: "SQL source",
        magic: "ASCII text",
        group: "code",
        mime: "application/x-sql",
        text: true,
    },
    Metadata {
        code: "squashfs",
        short: "squashfs",
        long: "Squash filesystem",
        magic: "Squashfs filesystem",
        group: "archive",
        mime: "application/octet-stream",
        text: false,
    },
    Metadata {
        code: "svg",
        short: "svg",
        long: "SVG Scalable Vector Graphics image data",
        magic: "SVG Scalable Vector Graphics image",
        group: "image",
        mime: "image/svg+xml",
        text: true,
    },
    Metadata {
        code: "swf",
        short: "swf",
        long: "Macromedia Flash data",
        magic: "Macromedia Flash data",
        group: "executable",
        mime: "application/x-shockwave-flash",
        text: false,
    },
    Metadata {
        code: "symlinktext",
        short: "symlinktext",
        long: "Symbolic link (textual representation)",
        magic: "ASCII text",
        group: "application",
        mime: "text/plain",
        text: true,
    },
    Metadata {
        code: "tar",
        short: "tar",
        long: "POSIX tar archive",
        magic: "POSIX tar archive",
        group: "archive",
        mime: "application/x-tar",
        text: false,
    },
    Metadata {
        code: "tga",
        short: "tga",
        long: "Targa image data",
        magic: "Targa image data",
        group: "image",
        mime: "image/x-tga",
        text: false,
    },
    Metadata {
        code: "tiff",
        short: "tiff",
        long: "TIFF image data",
        magic: "TIFF image data",
        group: "image",
        mime: "image/tiff",
        text: false,
    },
    Metadata {
        code: "torrent",
        short: "torrent",
        long: "BitTorrent file",
        magic: "BitTorrent file",
        group: "application",
        mime: "application/x-bittorrent",
        text: false,
    },
    Metadata {
        code: "ttf",
        short: "ttf",
        long: "TrueType Font data",
        magic: "TrueType Font data",
        group: "font",
        mime: "font/sfnt",
        text: false,
    },
    Metadata {
        code: "txt",
        short: "txt",
        long: "Generic text document",
        magic: "ASCII text",
        group: "text",
        mime: "text/plain",
        text: true,
    },
    Metadata {
        code: "unknown",
        short: "unknown",
        long: "Unknown binary data",
        magic: "data",
        group: "unknown",
        mime: "application/octet-stream",
        text: false,
    },
    Metadata {
        code: "vba",
        short: "vba",
        long: "MS Visual Basic source (VBA)",
        magic: "ASCII text",
        group: "code",
        mime: "text/vbscript",
        text: true,
    },
    Metadata {
        code: "wav",
        short: "wav",
        long: "Waveform Audio file (WAV)",
        magic: "RIFF data",
        group: "audio",
        mime: "audio/x-wav",
        text: false,
    },
    Metadata {
        code: "webm",
        short: "webm",
        long: "WebM data",
        magic: "WebM",
        group: "video",
        mime: "video/webm",
        text: false,
    },
    Metadata {
        code: "webp",
        short: "webp",
        long: "WebP data",
        magic: "RIFF data",
        group: "image",
        mime: "image/webp",
        text: false,
    },
    Metadata {
        code: "winregistry",
        short: "winregistry",
        long: "Windows Registry text",
        magic: "Windows Registry text",
        group: "application",
        mime: "text/x-ms-regedit",
        text: true,
    },
    Metadata {
        code: "wmf",
        short: "wmf",
        long: "Windows metafile",
        magic: "Windows metafile",
        group: "image",
        mime: "image/wmf",
        text: false,
    },
    Metadata {
        code: "xar",
        short: "xar",
        long: "XAR archive compressed data",
        magic: "xar archive compressed",
        group: "archive",
        mime: "application/x-xar",
        text: false,
    },
    Metadata {
        code: "xls",
        short: "xls",
        long: "Microsoft Excel CDF document",
        magic: "Composite Document File",
        group: "document",
        mime: "application/vnd.ms-excel",
        text: false,
    },
    Metadata {
        code: "xlsb",
        short: "xlsb",
        long: "Microsoft Excel 2007+ document (binary format)",
        magic: "Microsoft Excel 2007+",
        group: "document",
        mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        text: false,
    },
    Metadata {
        code: "xlsx",
        short: "xlsx",
        long: "Microsoft Excel 2007+ document",
        magic: "Microsoft Excel 2007+",
        group: "document",
        mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        text: false,
    },
    Metadata {
        code: "xml",
        short: "xml",
        long: "XML document",
        magic: "XML document",
        group: "code",
        mime: "text/xml",
        text: true,
    },
    Metadata {
        code: "xpi",
        short: "xpi",
        long: "Compressed installation archive (XPI)",
        magic: "Zip archive data",
        group: "archive",
        mime: "application/zip",
        text: false,
    },
    Metadata {
        code: "xz",
        short: "xz",
        long: "XZ compressed data",
        magic: "XZ compressed data",
        group: "archive",
        mime: "application/x-xz",
        text: false,
    },
    Metadata {
        code: "yaml",
        short: "yaml",
        long: "YAML source",
        magic: "ASCII text",
        group: "code",
        mime: "application/x-yaml",
        text: true,
    },
    Metadata {
        code: "zip",
        short: "zip",
        long: "Zip archive data",
        magic: "Zip archive data",
        group: "archive",
        mime: "application/zip",
        text: false,
    },
    Metadata {
        code: "zlibstream",
        short: "zlibstream",
        long: "zlib compressed data",
        magic: "zlib compressed data",
        group: "application",
        mime: "application/zlib",
        text: false,
    },
];
