[formatting]
column_width = 100
reorder_arrays = true
reorder_keys = true

[[rule]]
formatting = { reorder_keys = false }
keys = ["build-dependencies.*", "dependencies.*", "dev-dependencies.*", "package"]

[[rule]]
formatting = { reorder_arrays = false }
keys = ["package.metadata.deb"]
