[formatting]
column_width = 100
reorder_arrays = true
reorder_keys = true

[[rule]]
formatting = { reorder_keys = false }
keys = ["dependencies.*", "package"]

[[rule]]
formatting = { reorder_keys = true }
keys = ["package.*"]
