[package]
name = "magika-pyo3"
version = "2.0.0-dev"
edition = "2021"
publish = false

[lib]
name = "_magika"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.104"
magika = { path = "../lib" }
pyo3 = { version = "0.23", features = ["abi3-py38", "extension-module", "generate-import-lib"] }

[profile.release]
codegen-units = 1
lto = true

[profile.release-fast]
inherits = "release"
codegen-units = 16
lto = false


