name: cli vs python module tester

on:
  pull_request:

permissions:
  contents: read

jobs:
  run:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # pin@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.4.7/install.sh | sh
      - run: cargo build --release
        working-directory: rust/cli
      - run: rust/target/release/magika --json -r tests_data/basic
      # - run: python3 ./python/scripts/run_quick_test_magika_cli.py
      # - run: python3 ./python/scripts/run_quick_test_magika_module.py
      - name: Run "magika module" quick tests
        working-directory: python
        run: uv run --python 3.12 scripts/run_quick_test_magika_module.py