name: JS - generate docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ "main" ]
    paths:
      - 'js/**'
      - '.github/workflows/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  
jobs:

  makeDocs:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # pin@v4
        with:
          ref: main
      - name: Generate docs
        working-directory: js
        run: |
          yarn
          yarn run build
          yarn run make-docs
  
      - name: Commit
        run: |
          git config --local user.email "invernizzi.l@gmail.com"
          git config --local user.name "Luca Invernizzi"
          git commit -m "Update docs" -a
          git push
