name: JS - generate docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - "js/**"
      - ".github/workflows/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  makeDocs:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v4
        with:
          ref: main
      - name: Generate docs
        working-directory: js
        run: |
          yarn install --frozen-lockfile
          yarn run build
          yarn run make-docs

      - name: Commit
        run: |
          git config --local user.email "invernizzi.l@gmail.com"
          git config --local user.name "Luca Invernizzi"
          git commit -m "Update docs" -a
