name: JS - publish
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v4

      - name: Enable Corepack
        run: corepack enable

      - uses:  actions/setup-node@v6
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Build
        working-directory: js
        run: |
          yarn install --frozen-lockfile
          yarn run build
          yarn run test

      - name: Publish
        working-directory: js
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
