name: JS - tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'js/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'js/**'
      - '.github/workflows/**'
permissions:
  contents: read
jobs:
  unit-testing:
    strategy:
      matrix:
        node-version: [ "18", "20" ]
        os: [ "ubuntu-latest", "macos-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # pin@v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: js
        run: yarn
      - name: Build
        working-directory: js
        run: yarn run build
      - name: Run tests
        working-directory: js
        run: yarn test
