name: JS - tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'js/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'js/**'
      - '.github/workflows/**'
permissions:
  contents: read
jobs:
  unit-testing:
    strategy:
      matrix:
        node-version: [ "18", "20" ]
        os: [ "ubuntu-latest", "macos-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # pin@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: js
        run: yarn
      - name: Build
        working-directory: js
        run: yarn run build
      - name: Run tests
        working-directory: js
        run: yarn test
