name: JS - tests

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "js/**"
      - "tests_data/**"
      - ".github/workflows/js-*"
permissions:
  contents: read
jobs:
  unit-testing:
    strategy:
      matrix:
        node-version: ["18", "20"]
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # pin@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: js
        run: yarn install --frozen-lockfile
      - name: Build
        working-directory: js
        run: yarn run build
      - name: Run tests
        working-directory: js
        run: yarn test
