name: mypy
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths: [python]

jobs:
  unittesting:
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        - name: Install poetry
          uses: abatilo/actions-poetry@v2
          with:
            poetry-version: "1.7.1"
        - name: Install the project dependencies
          run: |
            cd python
            poetry install
        - name: Run mpy
          run: |
            cd python
            poetry run mypy magika tests