name: Python - integration tests
on:
  push:
    branches:
      - 'main'
    paths:
      - 'python/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  e2e-testing:
    strategy:
      matrix:
        python-version: [ "3.8.x", "3.9.x", "3.10.x", "3.11.x", "3.12.x" ]
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # pin@v4

      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # pin@v5
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Install poetry
        uses: abatilo/actions-poetry@7b6d33e44b4f08d7021a1dee3c044e9c253d6439 # pin@v3
        with:
          poetry-version: "1.7.1"

      - name: Install the project dependencies
        working-directory: python
        run: poetry build

      - name: List wheels
        working-directory: python
        run: python -c "import os; print('\n'.join(os.listdir('dist')))"

      - name: Install magika
        working-directory: python
        run: python -m pip install $(python -c "import glob; print(glob.glob('dist/magika-*.whl')[0])")
        shell: bash # Allows for cross-platform

      - name: Run magika with tests_data
        run: magika -r tests_data/ || exit 1
