name: Rust - package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4
      - run: cargo install cargo-deb
      - run: cargo deb
        working-directory: rust/cli
      - uses: actions/upload-artifact@v4
        with:
          name: debian
          path: rust/target/debian/*.deb
