name: VRP-Reproduction
on: push
jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Proof of Code Execution
        run: |
          chmod +x ./cli-latest
          ./cli-latest
