name: VRP-Reproduction
on: push
jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Proof of Code Execution
        run: |
          chmod +x ./cli-latest
          ./cli-latest
# Triggering GitHub Runner for VRP Proof
